### PR TITLE
Audio files from TSC meeting

### PR DESCRIPTION
**Pull request by KipTwitchell**
Signed-off-by: KipTwitchell <kip.twitchell@us.ibm.com>

@AOrthVector @jmertic , So I made a few mistakes in handling the video of the meeting and it resulted in losing the file.  @jmertic , how do I start zoom so that it is recorded on the server, rather than my local machine?  Also, can I (or you) share the zoom credentials with Andrea so that she can be my backup for the meetings?  

@AOrthVector , the audio files were preserved, but I think it would be good to get the slides from Randall to perhaps post in the meetings, and I think we should do an updated blog "activity" post on GenevaERS.org.  It could include (1) links to the TSC meetings minutes and videos for the TAC and the two TSC meetings, (2) and Randall's slides, (3) and the logo results.  We can also update the site with the new logos.  

Perhaps these should be separate issues, and I can make those if you'd like.

### CODE REVIEW

**Comment by jmertic** [comment]
@KipTwitchell - I adjusted the settings so that going forward recordings will be saved to the cloud instead. You'll get an email once they recording is done.

**Comment by KipTwitchell** [comment]
@AOrthVector I approved yours....so?

**Comment by AOrthVector** [comment]
GitHub is telling us that your branch is out of date with the base. I think you have to sync / fetch to local to get the latest updates; probably the TSC and redo the pull request.

I think

**Comment by AOrthVector** [comment]
Also, if you wouldn't mind, could you separate out the remaining items in the issue to new issues; help with me tracking what is left.

**Comment by AOrthVector** [comment]
> GitHub is telling us that your branch is out of date with the base. I think you have to sync / fetch to local to get the latest updates; probably the TSC and redo the pull request.
> 
> I think

Oh wait, I can probably take care of that.......please hold

**Comment by KipTwitchell** [comment]
OK, so updated the branch; but I'm sure it has not put the file in the right directory.  Could do that now, or on the next update after next week's meeting.

I also did put the other issues in different issues, so when we merge this we can close it.

**Comment by AOrthVector** [comment]
If you approve my latest pull request, everything should be fixed.
Also, the longer it waits, the more out of sync people's local and origin repositories will get and it can turn into a lot of work
Also, is there an approve button or something I should see when asked to do a review?

**Pull request closed without merging**
