### PR TITLE
Proposed options for review and comment

### PR DESCRIPTION
**Pull request by rhness**
Please review and comment on the options for Product Description.

### CODE REVIEW

**Review by jhornert — APPROVED** [review]

**Comment by neilbeesley** [comment]
I believe we should include a couple of short sentences using common industry language, even if we later change it. Gill and I came up with a few ideas..

**Comment by ghannington** [comment]
As Neil says I think we need something short that gets the key points across. For example something like:

GenevaERS rapidly produces many outputs while efficiently reading large data only once. It's reliability and performance is proven.
GenevaERS is extensible, adding more reports does not effect the performance. These are easily developed using a GUI.

**Comment by rhness** [comment]
How about this? 

GenevaERS rapidly produces many outputs while efficiently reading large volumes of data only once. Its reliability and performance is proven.  
GenevaERS is extensible, and adding more reports does not affect the performance. These are easily developed using a graphical interface.

**Comment by AOrthVector** [comment]
Concur with the other comments saying short with key points. Once someone is "in the door" we can get more detailed

**Comment by rhness** [comment]
**The final text is:** 

GenevaERS rapidly produces many outputs while efficiently reading large volumes of data only once.  
Its reliability and performance is proven. 
GenevaERS is extensible, and adding more reports does not affect the performance. These are easily developed using a graphical interface. 

The GenevaERS website (https://genevaers.org/) has been updated with this text.

**Pull request closed without merging**
