### PR TITLE
Create hook for self inviting one to a repo based on a comment

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Review by SaPeresi — APPROVED** [review]
Approve for commit

**Review by SaPeresi — APPROVED** [review]
Approve for commit

**Review by SaPeresi — APPROVED** [review]
Review and approve

**Review by SaPeresi — APPROVED** [review]
review and approve

**Review by KipTwitchell — APPROVED** [review]

**Pull request merged**
