### PR TITLE
Create Release.md

### PR DESCRIPTION
**Pull request by bobmcc9**
Created as initial copy

### CODE REVIEW

**Comment by AOrthVector** [comment]
Hey Bob, on this and the other pull request, if you come back to the request and click on the Details link to the right of the Required button, the link will tell you what you need to do to pass the checks

**Comment by bobmcc9** [comment]
G'day Andrea

a. thank you for this kind advice

b. I have the checks all passed now and have reviewers assigned

Cheerio,
bob


Bob McCormack 


 


Senior Software Engineer 
IBM Certified IT Specialist
Infrastructure : IBM Scalable Architect for Financial Reporting 
 



 

Australian Development Laboratory
1060 Hay St
West Perth
Australia 6005
 

Phone:
+61-8-92618554
 

Mobile                        0457 617228

 

e-mail:
bobmcc@au1.ibm.com

**Comment by AOrthVector** [comment]
Should prometheus be replaced by genevaers?

**Comment by bobmcc9** [comment]
I think the reference to https://github.com/prometheus/docs/pull/952/files
as it is an example of how a release is added

Mayhaps after this pull I will update this Release.md to clarify that point

**Review by AOrthVector — APPROVED** [review]

**Comment by bobmcc9** [comment]
My thanx to Andrea

I have removed the reference to prometheus in the Release.md concerning updating releases

**Pull request merged**
